services:
  syncer:
    restart: unless-stopped
    image: bpsoos/notion-dropbox-syncer
    environment:
      NDSYNCER_DROPBOX__APP_KEY: ""
      NDSYNCER_DROPBOX__APP_SECRET: ""
      NDSYNCER_DROPBOX__REFRESH_TOKEN: ""
      NDSYNCER_DROPBOX__FOLDER_PATH: ""
      NDSYNCER_NOTION__API_KEY: ""
      NDSYNCER_NOTION__DATABASE_ID: ""
